#! /bin/sh

########################################
#
#   ____ ____  ______        ____  __
#  | __ ) ___||  _ \ \      / /  \/  |
#  |  _ \___ \| |_) \ \ /\ / /| |\/| |
#  | |_) |__) |  __/ \ V  V / | |  | |
#  |____/____/|_|     \_/\_/  |_|  |_|
#
#
########################################

# Secondary

########################################

# Polybar
$HOME/.config/polybar/launch.sh &> /dev/null

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Disable beep
set -B

# Wallpaper
feh --bg-scale $(find ~/Wallpapers/current -type f | shuf -n 1)

# X Compositor
# May consume too much energy
#picom --config $HOME/.config/picom/picom.conf &

########################################
# __  __             _ _
#|  \/  | ___  _ __ (_) |_ ___  _ __
#| |\/| |/ _ \| '_ \| | __/ _ \| '__|
#| |  | | (_) | | | | | || (_) | |
#|_|  |_|\___/|_| |_|_|\__\___/|_|
#
########################################

#  You can use xrandr -q or bspc query -M --names to find the monitor names.
bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config gapless_monocle      true
bspc config borderless_monocle   true

# Colors
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1a1a1a"
bspc config focused_border_color	"#FFFFFF"
bspc config presel_feedback_color	"#5e81ac"

########################################

#__        __         _
#\ \      / /__  _ __| | _____ _ __   __ _  ___ ___  ___
# \ \ /\ / / _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \/ __|
#  \ V  V / (_) | |  |   <\__ \ |_) | (_| | (_|  __/\__ \
#   \_/\_/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___||___/
#                            #|_|
########################################


# Use this command and click over an specific application
# to see what its name
#xprop | grep WM_CLASS

bspc rule -a gimp desktop='^6' follow=on

########################################

# ____       _       _
#|  _ \ ___ | |_   _| |__   __ _ _ __
#| |_) / _ \| | | | | '_ \ / _` | '__|
#|  __/ (_) | | |_| | |_) | (_| | |
#|_|   \___/|_|\__, |_.__/ \__,_|_|
#              |___/

bscp rule -a polybar manage=off
