#! /bin/sh

########################################
#
#   ____ ____  ______        ____  __ 
#  | __ ) ___||  _ \ \      / /  \/  |
#  |  _ \___ \| |_) \ \ /\ / /| |\/| |
#  | |_) |__) |  __/ \ V  V / | |  | |
#  |____/____/|_|     \_/\_/  |_|  |_|
#
#
########################################

# May consume too much energy
# compton -b &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           12 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# _____                   _             _ 
#|_   _|__ _ __ _ __ ___ (_)_ __   __ _| |
  #| |/ _ \ '__| '_ ` _ \| | '_ \ / _` | |
  #| |  __/ |  | | | | | | | | | | (_| | |
  #|_|\___|_|  |_| |_| |_|_|_| |_|\__,_|_|

# Workspace for terminal
bspc rule -a Tilix desktop=^1 follow=on focus=on
bspc rule -a tilix desktop=^1 follow=on focus=on

#__        __         _                                  
#\ \      / /__  _ __| | _____ _ __   __ _  ___ ___  ___ 
 #\ \ /\ / / _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \/ __|
  #\ V  V / (_) | |  |   <\__ \ |_) | (_| | (_|  __/\__ \
   #\_/\_/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___||___/
                             #|_|

# Workspace for writing

# Office
bspc rule -a LibreOffice desktop=^2 follow=on focus=on
bspc rule -a libreoffice desktop=^2 follow=on focus=on
bspc rule -a LibreOffice --draw desktop=^2 follow=on focus=on
bspc rule -a libreoffice --draw desktop=^2 follow=on focus=on
bspc rule -a LibreOffice --calc desktop=^2 follow=on focus=on
bspc rule -a libreoffice --calc desktop=^2 follow=on focus=on
bspc rule -a LibreOffice --writer desktop=^2 follow=on focus=on
bspc rule -a libreoffice --writer desktop=^2 follow=on focus=on
bspc rule -a Gimp desktop=^2 follow=on focus=on state=fullscreen layer=below 
bspc rule -a gimp desktop=^2 follow=on focus=on state=fullscreen layer=below 

bspc rule -a Pcmanfm desktop=^2 follow=on focus=on layer=below 
bspc rule -a pcmanfm desktop=^2 follow=on focus=on layer=below 

#__        __   _       _                                         
#\ \      / /__| |__   | |__  _ __ _____      _____  ___ _ __ ___ 
 #\ \ /\ / / _ \ '_ \  | '_ \| '__/ _ \ \ /\ / / __|/ _ \ '__/ __|
  #\ V  V /  __/ |_) | | |_) | | | (_) \ V  V /\__ \  __/ |  \__ \
   #\_/\_/ \___|_.__/  |_.__/|_|  \___/ \_/\_/ |___/\___|_|  |___/

# Space for web browser
bspc rule -a firefox desktop=^3 follow=on focus=on
bspc rule -a tor-browser desktop=^3 follow=on focus=on

#  ____                                      _           _   _             
 #/ ___|___  _ __ ___  _ __ ___  _   _ _ __ (_) ___ __ _| |_(_) ___  _ __  
#| |   / _ \| '_ ` _ \| '_ ` _ \| | | | '_ \| |/ __/ _` | __| |/ _ \| '_ \ 
#| |__| (_) | | | | | | | | | | | |_| | | | | | (_| (_| | |_| | (_) | | | |
 #\____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|_|\___\__,_|\__|_|\___/|_| |_|


# Space for messages and conferences
bspc rule -a teams desktop=^4 follow=on focus=on
bspc rule -a Teams desktop=^4 follow=on focus=on
bspc rule -a steam desktop=^4 follow=on focus=on
bspc rule -a discord desktop=^4 follow=on focus=on
bspc rule -a TelegramDesktop desktop=^4 follow=on focus=on
bspc rule -a telegram-desktop desktop=^4 follow=on focus=on

#  ____                           
 #/ ___| __ _ _ __ ___   ___  ___ 
#| |  _ / _` | '_ ` _ \ / _ \/ __|
#| |_| | (_| | | | | | |  __/\__ \
 #\____|\__,_|_| |_| |_|\___||___/

 

 #____       _       _                
#|  _ \ ___ | |_   _| |__   __ _ _ __ 
#| |_) / _ \| | | | | '_ \ / _` | '__|
#|  __/ (_) | | |_| | |_) | (_| | |   
#|_|   \___/|_|\__, |_.__/ \__,_|_|   
              #|___/                  

bscp rule -a polybar manage=off

